package com.megapelis.images.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.megapelis.images.util.ImageConstant;
import lombok.*;

/**
 * @author yadir.garcia.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = ImageConstant.TABLA_NAME_BUSINESS)
public class Image {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String image;

    @DynamoDBAttribute
    private String createdDate;

    @DynamoDBAttribute
    private String lastModifiedDate;

}
